---
# tasks file for mysql-database-duplicator
- name: Dump database with name "{{ src_db_name }}" from "{{ src_db_host }}"
  community.mysql.mysql_db:
    name: "{{ src_db_name }}"
    state: dump
    target: "{{ dump_target }}"
    login_user: "{{ src_db_user }}"
    login_password: "{{ src_db_password }}"
    login_host: "{{ src_db_host }}"
    login_port: "{{ src_db_port }}"

- name: Drop database "{{ dest_db_name }}" on "{{ dest_db_host }}" if exist
  community.mysql.mysql_db:
    name: "{{ dest_db_name }}"
    state: absent
    login_user: "{{ dest_db_user }}"
    login_password: "{{ dest_db_password }}"
    login_host: "{{ dest_db_host }}"
    login_port: "{{ dest_db_port }}"

- name: Create database with name "{{ dest_db_name }}" on "{{ dest_db_host }}"
  community.mysql.mysql_db:
    name: "{{ dest_db_name }}"
    state: present
    login_user: "{{ dest_db_user }}"
    login_password: "{{ dest_db_password }}"
    login_host: "{{ dest_db_host }}"
    login_port: "{{ dest_db_port }}"

- name: Import database dump file to "{{ dest_db_name }}"
  community.mysql.mysql_db:
    name: "{{ dest_db_name }}"
    state: import
    target: "{{ dump_target }}"
    login_user: "{{ dest_db_user }}"
    login_password: "{{ dest_db_password }}"
    login_host: "{{ dest_db_host }}"
    login_port: "{{ dest_db_port }}"

- name: Cleanup up database dumped file
  ansible.builtin.file:
    path: "{{ dump_target }}"
    state: absent
